language: java
jdk:
 - openjdk6
 - oraclejdk7
script: mvn clean install --batch-mode
matrix:
  allow_failures:
    - jdk: oraclejdk7
branches:
  only:
    - master
after_success:
  - mvn jacoco:report coveralls:report
notifications:
  email: false
sudo: false
